import type { Metadata } from "next";
import Link from "next/link";
import { generateSeoMeta } from "@/utils/seo";

interface Props {
  params: Promise<{ lang: string }>;
}

export async function generateMetadata({ params }: Props): Promise<Metadata> {
  const { lang } = await params;
  const isAr = lang === "ar";
  return generateSeoMeta({
    title: isAr ? "سياسة الخصوصية — ورشتي" : "Privacy Policy — Warshety",
    description: isAr
      ? "اقرأ سياسة الخصوصية الخاصة بورشتي وتعرّف على كيفية جمعنا لبياناتك واستخدامها وحمايتها."
      : "Read Warshety's Privacy Policy and learn how we collect, use, and protect your personal data.",
    path: "/legal/privacy",
    locale: isAr ? "ar" : "en",
  });
}

const SECTIONS = [
  {
    numAr: "١",
    numEn: "1",
    titleAr: "مقدمة",
    titleEn: "Introduction",
    bodyAr:
      "مرحبًا بك في ورشتي. نحن نحترم خصوصيتك ونلتزم بحماية بياناتك الشخصية. توضح هذه السياسة كيفية جمعنا لمعلوماتك واستخدامها وحمايتها عند استخدام منصتنا.",
    bodyEn:
      "Welcome to Warshety. We respect your privacy and are committed to protecting your personal data. This policy explains how we collect, use, and protect your information when you use our platform.",
  },
  {
    numAr: "٢",
    numEn: "2",
    titleAr: "المعلومات التي نجمعها",
    titleEn: "Information We Collect",
    bodyAr:
      "نجمع المعلومات التي تقدمها مباشرةً (الاسم، البريد الإلكتروني، رقم الهاتف، بيانات المركبة) والمعلومات الناتجة عن استخدامك للخدمة (سجل الحجوزات، سجل الطلبات، بيانات الموقع عند البحث عن مراكز خدمة قريبة).",
    bodyEn:
      "We collect information you provide directly (name, email, phone, vehicle details) and information generated by your use of the Service (booking history, order history, location data when you search for nearby service centers).",
  },
  {
    numAr: "٣",
    numEn: "3",
    titleAr: "كيف نستخدم معلوماتك",
    titleEn: "How We Use Your Information",
    bodyAr:
      "نستخدم معلوماتك لمعالجة الطلبات والحجوزات، وتخصيص تجربتك، وإرسال الإشعارات المتعلقة بالمعاملات، وتحسين المنصة، والامتثال للالتزامات القانونية.",
    bodyEn:
      "We use your information to process orders and bookings, personalise your experience, send transactional notifications, improve the platform, and comply with legal obligations.",
  },
  {
    numAr: "٤",
    numEn: "4",
    titleAr: "مشاركة المعلومات",
    titleEn: "Sharing of Information",
    bodyAr:
      "نشارك معلوماتك مع البائعين فقط بالقدر اللازم لتنفيذ طلبك أو حجزك. قد نشارك البيانات مع معالجي المدفوعات وشركاء الخدمات اللوجستية ومزودي التحليلات بموجب اتفاقيات معالجة بيانات صارمة. لا نبيع بياناتك الشخصية لأطراف ثالثة.",
    bodyEn:
      "We share your information with vendors only to the extent necessary to fulfil your order or booking. We may share data with payment processors, logistics partners, and analytics providers under strict data-processing agreements. We do not sell your personal data to third parties.",
  },
  {
    numAr: "٥",
    numEn: "5",
    titleAr: "ملفات تعريف الارتباط",
    titleEn: "Cookies",
    bodyAr:
      "نستخدم ملفات تعريف الارتباط والتقنيات المشابهة للحفاظ على جلستك، وتذكر تفضيلات اللغة، وتحليل حركة الموقع. يمكنك التحكم في ملفات تعريف الارتباط من خلال إعدادات المتصفح.",
    bodyEn:
      "We use cookies and similar technologies to maintain your session, remember your language preference, and analyse site traffic. You can control cookies through your browser settings.",
  },
  {
    numAr: "٦",
    numEn: "6",
    titleAr: "الاحتفاظ بالبيانات",
    titleEn: "Data Retention",
    bodyAr:
      "نحتفظ ببياناتك الشخصية طالما كان حسابك نشطًا أو حسب الحاجة لتقديم الخدمات. يمكنك طلب حذف حسابك والبيانات المرتبطة به عن طريق التواصل مع فريق الدعم.",
    bodyEn:
      "We retain your personal data for as long as your account is active or as needed to provide services. You may request deletion of your account and associated data by contacting our support team.",
  },
  {
    numAr: "٧",
    numEn: "7",
    titleAr: "الأمان",
    titleEn: "Security",
    bodyAr:
      "نطبق معايير أمنية على مستوى الصناعة تشمل التشفير أثناء النقل (TLS) وفي حالة السكون. ومع ذلك، لا يوجد نظام آمن تمامًا ولا يمكننا ضمان الأمان المطلق.",
    bodyEn:
      "We implement industry-standard security measures including encryption in transit (TLS) and at rest. However, no system is completely secure and we cannot guarantee absolute security.",
  },
  {
    numAr: "٨",
    numEn: "8",
    titleAr: "حقوقك",
    titleEn: "Your Rights",
    bodyAr:
      "يحق لك الوصول إلى بياناتك الشخصية أو تصحيحها أو حذفها. كما يحق لك الاعتراض على معالجة بياناتك في حالات معينة أو طلب تقييدها. لممارسة هذه الحقوق يُرجى التواصل معنا.",
    bodyEn:
      "You have the right to access, correct, or delete your personal data. You may also object to or restrict processing in certain circumstances. To exercise these rights, please contact us.",
  },
  {
    numAr: "٩",
    numEn: "9",
    titleAr: "خصوصية الأطفال",
    titleEn: "Children's Privacy",
    bodyAr:
      "خدماتنا غير موجهة للأشخاص دون سن 18 عامًا. لا نجمع عن قصد أي بيانات شخصية من الأطفال. إذا علمنا بجمع بيانات طفل دون موافقة الوالدين، سنحذفها فورًا.",
    bodyEn:
      "Our services are not directed to persons under 18. We do not knowingly collect personal data from children. If we become aware that a child's data has been collected without parental consent, we will delete it immediately.",
  },
  {
    numAr: "١٠",
    numEn: "10",
    titleAr: "روابط الأطراف الثالثة",
    titleEn: "Third-Party Links",
    bodyAr:
      "قد تحتوي منصتنا على روابط لمواقع أطراف ثالثة. لسنا مسؤولين عن ممارسات الخصوصية الخاصة بهذه المواقع ونشجعك على مراجعة سياسات الخصوصية الخاصة بها.",
    bodyEn:
      "Our platform may contain links to third-party websites. We are not responsible for the privacy practices of those sites and encourage you to review their privacy policies.",
  },
  {
    numAr: "١١",
    numEn: "11",
    titleAr: "التغييرات على هذه السياسة",
    titleEn: "Changes to This Policy",
    bodyAr:
      "قد نقوم بتحديث سياسة الخصوصية هذه بشكل دوري. سنخطرك بالتغييرات الجوهرية عبر البريد الإلكتروني أو إشعار بارز على المنصة.",
    bodyEn:
      "We may update this Privacy Policy periodically. We will notify you of significant changes via email or a prominent notice on the platform.",
  },
  {
    numAr: "١٢",
    numEn: "12",
    titleAr: "القانون الحاكم",
    titleEn: "Governing Law",
    bodyAr: "تخضع هذه السياسة لقوانين جمهورية مصر العربية.",
    bodyEn:
      "This Policy is governed by the laws of the Arab Republic of Egypt.",
  },
  {
    numAr: "١٣",
    numEn: "13",
    titleAr: "تواصل معنا",
    titleEn: "Contact Us",
    bodyAr: "لأي استفسارات تتعلق بخصوصيتك، تواصل معنا على",
    bodyEn: "For any privacy-related questions, contact us at",
    isContact: true,
    contactEmail: "support@warshety.com",
  },
];

export default async function PrivacyPage({ params }: Props) {
  const { lang } = await params;
  const isAr = lang === "ar";

  return (
    <div
      className="min-h-screen bg-[#f6f6f8] dark:bg-[#111621]"
      dir={isAr ? "rtl" : "ltr"}
      lang={lang}
    >
      {/* Hero */}
      <section className="bg-slate-950 text-white">
        <div className="max-w-5xl mx-auto px-6 py-16">
          <nav className="text-xs text-slate-400 mb-6 flex items-center gap-2">
            <Link
              href={`/${lang}`}
              className="hover:text-[#FF4B19] transition-colors"
            >
              {isAr ? "الرئيسية" : "Home"}
            </Link>
            <span>/</span>
            <span className="text-slate-300">
              {isAr ? "سياسة الخصوصية" : "Privacy Policy"}
            </span>
          </nav>
          <span className="inline-block text-[#FF4B19] text-xs font-semibold tracking-widest uppercase mb-3">
            {isAr ? "قانوني" : "Legal"}
          </span>
          <h1 className="text-4xl md:text-5xl font-black mb-3">
            {isAr ? "سياسة الخصوصية" : "Privacy Policy"}
          </h1>
          <p className="text-slate-400 text-sm">
            {isAr ? "آخر تحديث: أبريل ٢٠٢٦" : "Last updated: April 2026"}
          </p>
        </div>
      </section>

      {/* Content */}
      <div className="max-w-5xl mx-auto px-6 py-14 grid md:grid-cols-[240px_1fr] gap-12">
        {/* Sidebar TOC */}
        <aside className="hidden md:block">
          <div className="sticky top-8 bg-white dark:bg-slate-900 rounded-2xl border border-slate-200 dark:border-slate-800 p-5">
            <p className="text-xs font-semibold text-slate-500 uppercase tracking-widest mb-4">
              {isAr ? "المحتويات" : "Contents"}
            </p>
            <ul className="space-y-2">
              {SECTIONS.map((s) => (
                <li key={s.numEn}>
                  <a
                    href={`#section-${s.numEn}`}
                    className="text-xs text-slate-500 hover:text-[#FF4B19] transition-colors flex gap-2"
                  >
                    <span className="text-[#FF4B19] font-bold shrink-0">
                      {isAr ? s.numAr : s.numEn}.
                    </span>
                    {isAr ? s.titleAr : s.titleEn}
                  </a>
                </li>
              ))}
            </ul>
          </div>
        </aside>

        {/* Sections */}
        <main className="space-y-6">
          {SECTIONS.map((s) => (
            <section
              key={s.numEn}
              id={`section-${s.numEn}`}
              className="bg-white dark:bg-slate-900 rounded-2xl border border-slate-200 dark:border-slate-800 p-7"
            >
              <div className="flex items-start gap-4">
                <span className="shrink-0 w-9 h-9 rounded-xl bg-[#FF4B19]/10 text-[#FF4B19] font-black text-sm flex items-center justify-center">
                  {isAr ? s.numAr : s.numEn}
                </span>
                <div>
                  <h2 className="font-black text-slate-900 dark:text-white mb-2">
                    {isAr ? s.titleAr : s.titleEn}
                  </h2>
                  <p className="text-sm text-slate-600 dark:text-slate-400 leading-relaxed">
                    {isAr ? s.bodyAr : s.bodyEn}
                    {s.isContact && (
                      <>
                        {" "}
                        <a
                          href={`mailto:${s.contactEmail}`}
                          className="text-[#FF4B19] hover:underline"
                        >
                          {s.contactEmail}
                        </a>
                        .
                      </>
                    )}
                  </p>
                </div>
              </div>
            </section>
          ))}

          {/* Link to Terms */}
          <div className="bg-slate-950 text-white rounded-2xl p-7 flex flex-col sm:flex-row items-center justify-between gap-4">
            <div>
              <p className="font-bold mb-1">
                {isAr ? "الشروط والأحكام" : "Terms & Conditions"}
              </p>
              <p className="text-sm text-slate-400">
                {isAr
                  ? "اقرأ الشروط التي تحكم استخدامك لمنصة ورشتي."
                  : "Read the terms that govern your use of the Warshety platform."}
              </p>
            </div>
            <Link
              href={`/${lang}/legal/terms`}
              className="shrink-0 bg-[#FF4B19] text-white px-5 py-2.5 rounded-lg font-semibold text-sm hover:bg-[#e04316] transition-colors"
            >
              {isAr ? "اقرأ الشروط" : "Read Terms"}
            </Link>
          </div>
        </main>
      </div>
    </div>
  );
}
